name: Deploy page to server
on: push
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Clone repo on deployment server
        env:
          SSH_KEY: ${{ secrets.SSH_KEY }}
        run: |
          echo "${{ secrets.SSH_KEY }}" > /tmp/ssh-key
          chmod 0600 /tmp/ssh-key
          eval `ssh-agent`
          ssh-add /tmp/ssh-key
          ssh -A -o StrictHostKeyChecking=no root@server.talk-about-it.ca \
          "cd /var/www/havetheyelopedyet.ca; git pull"